### ISSUE TITLE
Code about Generating Point Cloud from Mesh for ShapeNet dataset

### ISSUE THREAD

**Issue by LongLong-Jing** [AnTao97/PointCloudDataset#1]
Hi @AnTao97,

Thanks for your amazing work. The point cloud data are very useful. I am wondering can you also share the code to generate a point cloud from mesh data for ShapeNet dataset? Thanks!

**Comment by AnTao97** [comment]
Thanks for your appreciation!

You can send me an email to ta19@mails.tsinghua.edu.cn. I will reply to you with my code.

**Comment by antao97** [comment]
Thanks for your appreciation!

In fact, I use the generated ShapeNet point clouds (15k points per shape) from https://drive.google.com/drive/folders/1G0rf-6HSHoTll6aH7voh-dXj6hCRhSAQ?usp=sharing in https://github.com/stevenygd/PointFlow. I then use FPS to sample 2048 points from 15k.

**Comment by LongLong-Jing** [comment]
Hi @AnTao97,

Thanks for your quick response.
