### ISSUE TITLE
[Code Improvements] Label Nums in Segmentation Not Match the Point Clouds Nums

### ISSUE THREAD

**Issue by Chenguoz** [AnTao97/PointCloudDataset#12]
In the segmentation task, if the number of input point cloud points is less than 2048, the number of labels obtained should be the same as the number of input point cloud, but the code still returns labels for all points.
We just need to change line 178 of the code
```
seg = self.seg[item]
```
to
```
seg = self.seg[item][:self.num_points]
```
:)

**Comment by antao97** [comment]
Thanks for your reminder! I have fixed this part in the updated code.
