### ISSUE TITLE
[BUG Report]Motorbike Class Name Error in ShapeNetPart

### ISSUE THREAD

**Issue by Chenguoz** [AnTao97/PointCloudDataset#13]
The key for motorbike in the code is ``motor``, while in the shapenetpart dataset, the key is ``motorbike``, so the mapping of the code dictionary shapenetpart_cat2id should be changed to motorbike.
The correct mapping is as follows
```
shapenetpart_cat2id = {..., 'motorbike': 10, ...}
```

**Comment by antao97** [comment]
Thanks for your reminder! I have fixed this now.
