### ISSUE TITLE
maybe mismatch for 'shapenetcorev2'

### ISSUE THREAD

**Issue by jumptiger66** [AnTao97/PointCloudDataset#14]
Thanks for your amazing work , and it helps me a lot .
I try to use this dataset for classification task. However , I think that there are some mismatches about variable " self.path_file_all " , " self.path_h5py_all " and " self.path_name_all " . Specifically , after runing the program , I obtained the list order shown in Figure 1, which is the order of variable  " self.path_file_all " and " self.path_name_all ".Figure2 shows variable " self.path_h5py_all " 's list order. Obviously， train10_idfile.json can't match train1.h5 . The code <self.path_name_all.sort()> causes these chaos of order . Althrough , The absence of these two variables does not affect the use of the dataset, because the corresponding relationship between data and label is correctly saved in  variable  "self.path_h5py_all " . If i misunderstand the code , please forgive me.
![QQ图片20220919161543](https://user-images.githubusercontent.com/68233344/190976455-9b2e1709-975d-4a7e-8a25-ea01fbce2d7b.png)
![QQ图片20220919161556](https://user-images.githubusercontent.com/68233344/190976480-d19596b9-05e9-4ac8-bc0f-c9cb31d27139.png)

**Comment by antao97** [comment]
Thanks for your feedback! I have fixed this mistake in the updated code.
