### ISSUE TITLE
Visualize point cloud

### ISSUE THREAD

**Issue by Jibanul** [AnTao97/PointCloudDataset#15]
Hello, thanks for sharing the datasets. Could you please share how you visualized point clouds as shown on your project description page? They look very nice and fancy. Just wondering. Thanks.

**Comment by antao97** [comment]
To visualize, run `visualize.py` to generate XML file and use [Mitsuba](https://www.mitsuba-renderer.org/index.html) to render it.

**Comment by Jibanul** [comment]
Thank you.
