### ISSUE TITLE
Understanding ShapeNet results

### ISSUE THREAD

**Issue by QenSchr** [AnTao97/PointCloudDataset#2]
Hello @AnTao97 , with which split did you achieve the results on the ShapeNetCore dataset? Did you reach the 96.8% on the test data set? Thanks!

**Comment by AnTao97** [comment]
Sorry, I can't get your point. This repo only contains some arranged datasets.

**Comment by antao97** [comment]
So are you saying the result in [AnTao97/UnsupervisedPointCloudReconstruction](https://github.com/AnTao97/UnsupervisedPointCloudReconstruction)? I use all data from ShapeNetCore dataset to train my model, and then extract trained feature for each point cloud. Next, I train a linear SVM classifier based on the extracted features and reach the 96.8% acc in classification. This task is used to evaluate the degree of performance drop when the feature extractor and the linear SVM classifier are trained on different dataset. The "ShapeNetCore.v2" column means they are both trained on ShapeNetCore dataset. The "ModelNet40" column means the feature extractor is trained on ShapeNetCore dataset, while the linear SVM classifier is trained on ModelNet40 dataset.

**Comment by QenSchr** [comment]
Hi @AnTao97, thanks for your quick response. Yes, I meant AnTao97/UnsupervisedPointCloudReconstruction. My question has been answered.
