### ISSUE TITLE
Dataset centered and scaled  ? 

### ISSUE THREAD

**Issue by odie2630463** [AnTao97/PointCloudDataset#3]
Thanks you ! It help me a lot for my research. But I wonder know all points are centered and scaled by which value ?

**Comment by antao97** [comment]
A point cloud is centered according to its central location (calculated by averaging the XYZ locations of all points) and scaled according to the maximum distance from the central location to the farthest point. After transformation, the distances from all points in a point cloud to the origin of coordinates are range from [0, 1].

**Comment by odie2630463** [comment]
HI , all points mean whole datasets ? Or just one object ? I need to denormalize the point back to the original ShapeNet , do you have the mean and  maximum distance value ? 

Thanks a lot !

**Comment by antao97** [comment]
for each object

**Comment by odie2630463** [comment]
Thanks ! I know how to recompute it.
