### ISSUE TITLE
The question of ShapeNetCore.v2 dataset

### ISSUE THREAD

**Issue by zwy1996** [AnTao97/PointCloudDataset#4]
Hi, nice job!

When I  downloaded the ShapeNetCore.v2 dataset, I found that the baidu pan was lost.
Could you please offer the new link of baidu pan?

Thank you very much!

**Comment by antao97** [comment]
I checked the Baidu pan link. The link is successfully opened in my browser.

**Comment by zwy1996** [comment]
Hi,

Thanks for your response in time! I can download dataset normally when I closed the VPN.

Thank you!
