### ISSUE TITLE
Your shapenetcorev2 dataset don't have segmentation information

### ISSUE THREAD

**Issue by yuchenlichuck** [AnTao97/PointCloudDataset#5]
hi, I checked your shapenetcorev2 dataset, I find there is no segmentation information. Could you add the segmentation information? Thanks a lot!

**Comment by antao97** [comment]
The segmentation is only added to shapenet part dataset. See paper `A scalable active framework for region annotation in 3D shape collections` for more details.

**Comment by yuchenlichuck** [comment]
Yes, Thanks a lot! I find it!. I think your code in dataset.py allow shapenetcorev2 to have segmentation, it may need to delete.

**Comment by antao97** [comment]
I have updated the code. Thanks for your feedback!
