### ISSUE TITLE
id_choice in dataset.py is not defined

### ISSUE THREAD

**Issue by yuchenlichuck** [AnTao97/PointCloudDataset#6]
I found that if we class_choice and use segmentation there is an _id_choice_, which is not defined. I think It may be the _indices_. could you check with it?

**Comment by yuchenlichuck** [comment]
BTW, Thanks for your excellent work, it largely improved my data loading efficiency. Thank you so much!

**Comment by yuchenlichuck** [comment]
And  Do you have the data that concentrate the XYZ axis with the normal vector (6-dim)?

**Comment by antao97** [comment]
Thanks for your feedback! I have fixed the bug and uploaded the code.

Note that `id_choice` is not `indices`. See my new code and https://github.com/AnTao97/dgcnn.pytorch/issues/10 for details.

I don't have data with normal vectors. You can generate your own dataset with normal vectors.

**Comment by yuchenlichuck** [comment]
Do you know how to get the normal vectors from the original dataset?

**Comment by antao97** [comment]
Since the point clouds are obtained on mesh, you can calculate the normal vectors on the mesh and then cast them into point clouds.

**Comment by yuchenlichuck** [comment]
Sure, thanks a lot
